# Generated by Django 4.2.23 on 2025-07-26 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0003_otp'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisteredUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='Full name as per government ID', max_length=200)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('voter_id_epic', models.CharField(help_text='Voter ID EPIC number', max_length=20, unique=True)),
                ('aadhaar_number', models.CharField(help_text='Aadhar card number', max_length=12, unique=True)),
                ('guardian_name', models.CharField(help_text='Father/Mother/Husband name as per voter ID', max_length=200)),
                ('guardian_relation', models.CharField(choices=[('father', 'Father'), ('mother', 'Mother'), ('husband', 'Husband')], max_length=10)),
                ('phone_number', models.CharField(help_text='Registered phone number', max_length=15, unique=True)),
                ('email', models.EmailField(blank=True, help_text='Email address (optional)', max_length=254, null=True)),
                ('address', models.TextField(help_text="Voter's complete address")),
                ('constituency', models.CharField(help_text='Voting constituency', max_length=200)),
                ('aadhaar_image', models.ImageField(help_text='Upload Aadhar card image', upload_to='user_documents/aadhaar/')),
                ('voter_id_image', models.ImageField(help_text='Upload Voter ID image', upload_to='user_documents/voter_id/')),
                ('phone_verified', models.BooleanField(default=False)),
                ('documents_verified', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('linked_voter', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='voting.voter')),
            ],
            options={
                'verbose_name': 'Registered User',
                'verbose_name_plural': 'Registered Users',
            },
        ),
        migrations.DeleteModel(
            name='DigiLockerUser',
        ),
    ]
