# Generated by Django 4.2.23 on 2025-11-02 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0004_registereduser_delete_digilockeruser'),
    ]

    operations = [
        migrations.CreateModel(
            name='FederatedModelVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(help_text='Semantic version (e.g., v1.2.3)', max_length=20, unique=True)),
                ('model_weights', models.JSONField(help_text='Aggregated weights from federated training')),
                ('num_participants', models.IntegerField(default=0, help_text='Number of clients contributing to this version')),
                ('average_loss', models.FloatField(blank=True, help_text='Average training loss', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=False, help_text='Currently deployed model version')),
                ('deployment_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Release notes or change description')),
            ],
            options={
                'verbose_name': 'Federated Model Version',
                'verbose_name_plural': 'Federated Model Versions',
                'db_table': 'federated_model_versions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BiometricEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_embedding', models.BinaryField(help_text='Encrypted 128-dimensional face embedding vector')),
                ('embedding_hash', models.CharField(db_index=True, help_text='SHA-256 hash for deduplication', max_length=64, unique=True)),
                ('confidence_score', models.FloatField(help_text='Face detection confidence (0-1)')),
                ('model_version', models.CharField(help_text='Federated model version used', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used', models.DateTimeField(blank=True, help_text='Last successful authentication', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Can be used for authentication')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biometric_embeddings', to='voting.voter')),
            ],
            options={
                'verbose_name': 'Biometric Embedding',
                'verbose_name_plural': 'Biometric Embeddings',
                'db_table': 'biometric_embeddings',
            },
        ),
        migrations.CreateModel(
            name='BiometricAuthLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('success', models.BooleanField(help_text='Authentication result')),
                ('similarity_score', models.FloatField(help_text='Cosine similarity score')),
                ('model_version', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('failure_reason', models.CharField(blank=True, help_text='Reason for authentication failure', max_length=100)),
                ('embedding', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='voting.biometricembedding')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_logs', to='voting.voter')),
            ],
            options={
                'verbose_name': 'Biometric Authentication Log',
                'verbose_name_plural': 'Biometric Authentication Logs',
                'db_table': 'biometric_auth_logs',
            },
        ),
        migrations.CreateModel(
            name='FederatedGradientContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gradient_data', models.JSONField(help_text='Differential-privacy protected gradients')),
                ('loss', models.FloatField(help_text='Local training loss')),
                ('num_samples', models.IntegerField(help_text='Number of local samples used')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('included_in_aggregation', models.BooleanField(default=False, help_text='Included in federated averaging')),
                ('aggregation_date', models.DateTimeField(blank=True, null=True)),
                ('model_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='voting.federatedmodelversion')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gradient_contributions', to='voting.voter')),
            ],
            options={
                'verbose_name': 'Federated Gradient Contribution',
                'verbose_name_plural': 'Federated Gradient Contributions',
                'db_table': 'federated_gradient_contributions',
                'indexes': [models.Index(fields=['model_version', 'included_in_aggregation'], name='federated_g_model_v_92d14f_idx'), models.Index(fields=['submitted_at'], name='federated_g_submitt_9b6a6e_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='biometricembedding',
            index=models.Index(fields=['voter', 'model_version', 'is_active'], name='biometric_e_voter_i_23dc7e_idx'),
        ),
        migrations.AddIndex(
            model_name='biometricembedding',
            index=models.Index(fields=['embedding_hash'], name='biometric_e_embeddi_5cc064_idx'),
        ),
        migrations.AddIndex(
            model_name='biometricembedding',
            index=models.Index(fields=['created_at'], name='biometric_e_created_5c16a5_idx'),
        ),
        migrations.AddIndex(
            model_name='biometricauthlog',
            index=models.Index(fields=['voter', 'timestamp'], name='biometric_a_voter_i_afd3d8_idx'),
        ),
        migrations.AddIndex(
            model_name='biometricauthlog',
            index=models.Index(fields=['success', 'timestamp'], name='biometric_a_success_8f1c55_idx'),
        ),
    ]
