# Generated by Django 4.2.23 on 2025-11-02 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0005_federatedmodelversion_biometricembedding_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLiteracyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('literacy_level', models.CharField(choices=[('advanced', 'Advanced (College+)'), ('intermediate', 'Intermediate (High School)'), ('basic', 'Basic (Primary Education)'), ('minimal', 'Minimal (Limited Reading)'), ('visual', 'Visual Learner (Prefers Images)')], default='intermediate', max_length=20)),
                ('preferred_language', models.CharField(default='en', max_length=10)),
                ('font_size_preference', models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large'), ('xlarge', 'Extra Large')], default='medium', max_length=10)),
                ('use_audio_assistance', models.BooleanField(default=False)),
                ('use_visual_aids', models.BooleanField(default=True)),
                ('cognitive_assistance_enabled', models.BooleanField(default=False)),
                ('assessed_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('total_interactions', models.IntegerField(default=0)),
                ('help_requests_count', models.IntegerField(default=0)),
                ('average_reading_time', models.FloatField(blank=True, null=True)),
                ('voter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='literacy_profile', to='voting.voter')),
            ],
            options={
                'verbose_name': 'User Literacy Profile',
                'verbose_name_plural': 'User Literacy Profiles',
                'db_table': 'user_literacy_profiles',
            },
        ),
        migrations.CreateModel(
            name='SimplifiedBallotContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('literacy_level', models.CharField(choices=[('advanced', 'Advanced (College+)'), ('intermediate', 'Intermediate (High School)'), ('basic', 'Basic (Primary Education)'), ('minimal', 'Minimal (Limited Reading)'), ('visual', 'Visual Learner (Prefers Images)')], max_length=20)),
                ('language', models.CharField(default='en', max_length=10)),
                ('simple_name', models.CharField(max_length=200)),
                ('simple_party_description', models.TextField()),
                ('key_points', models.JSONField(default=list)),
                ('simple_manifesto', models.TextField(blank=True)),
                ('analogies', models.JSONField(default=list)),
                ('visual_summary_path', models.CharField(blank=True, max_length=500)),
                ('infographic_path', models.CharField(blank=True, max_length=500)),
                ('audio_description_path', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simplified_content', to='voting.candidate')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simplified_content', to='voting.party')),
            ],
            options={
                'db_table': 'simplified_ballot_content',
                'indexes': [models.Index(fields=['candidate', 'literacy_level'], name='simplified__candida_3e125c_idx'), models.Index(fields=['party', 'literacy_level'], name='simplified__party_i_559cd4_idx')],
                'unique_together': {('candidate', 'literacy_level', 'language')},
            },
        ),
        migrations.CreateModel(
            name='BallotInteractionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.CharField(choices=[('view', 'Viewed Candidate'), ('help', 'Requested Help'), ('simplify', 'Requested Simplification'), ('audio', 'Played Audio'), ('translate', 'Changed Language')], max_length=50)),
                ('time_spent', models.FloatField(help_text='Time in seconds')),
                ('literacy_level_at_time', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.candidate')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.voter')),
            ],
            options={
                'db_table': 'ballot_interaction_logs',
                'indexes': [models.Index(fields=['voter', 'timestamp'], name='ballot_inte_voter_i_b38682_idx')],
            },
        ),
    ]
