"""
Django settings for vote4all project.

Generated by 'django-admin startproject' using Django 4.2.23.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-4-evnosv1s-44+ca&f6+s0@c60ws%a0i!@y!5&%!28m5_z)+k4'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'voting',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',  # Add locale middleware for i18n
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'vote4all.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'vote4all.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases


# Use SQLite for local development by default
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en'

# Supported languages for the voting application
LANGUAGES = [
    ('en', 'English'),
    ('hi', 'हिन्दी'),
    ('bn', 'বাংলা'),
    ('te', 'తెలుగు'),
    ('mr', 'मराठी'),
    ('ta', 'தமிழ்'),
    ('gu', 'ગુજરાતી'),
    ('kn', 'ಕನ್ನಡ'),
    ('ml', 'മലയാളം'),
    ('pa', 'ਪੰਜਾਬੀ'),
    ('or', 'ଓଡ଼ିଆ'),
    ('as', 'অসমীয়া'),
    ('ur', 'اردو'),
]

# Locale paths
LOCALE_PATHS = [
    BASE_DIR / 'locale',
]

TIME_ZONE = 'Asia/Kolkata'  # Indian timezone

USE_I18N = True
USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ============================================================
# FEDERATED LEARNING CONFIGURATION
# Privacy-Preserving Biometric Authentication
# ============================================================

# Biometric Encryption Key (IMPORTANT: Keep this SECRET!)
# For production, use environment variable: os.getenv('BIOMETRIC_ENCRYPTION_KEY')
# This key was generated using cryptography.fernet.Fernet.generate_key()
BIOMETRIC_ENCRYPTION_KEY = 'Y2riBqAizjxPlPfHzkozofbHLean28oxBkvEKGp_nF4='  # Generated key - keep secret!

# Federated Learning Parameters
FEDERATED_LEARNING = {
    'MIN_PARTICIPANTS': 10,  # Minimum number of clients before aggregation
    'DIFFERENTIAL_PRIVACY_EPSILON': 1.0,  # Privacy budget (lower = more private)
    'MODEL_UPDATE_FREQUENCY': 'weekly',  # How often to aggregate gradients
    'CLIENT_MODEL_VERSION': 'v1.0.0',  # Current model version for clients
    'GRADIENT_CLIP_NORM': 1.0,  # Gradient clipping for stability
    'LEARNING_RATE': 0.01,  # Learning rate for federated updates
}

# Biometric Verification Settings
BIOMETRIC_VERIFICATION = {
    'SIMILARITY_THRESHOLD': 0.6,  # Cosine similarity threshold for authentication (0-1)
    'MIN_CONFIDENCE': 0.5,  # Minimum face detection confidence required
    'MAX_ATTEMPTS': 3,  # Maximum failed authentication attempts before lockout
    'LOCKOUT_DURATION': 900,  # Lockout duration in seconds (15 minutes)
    'EMBEDDING_DIMENSION': 128,  # FaceAPI descriptor dimension
}

# Privacy and Compliance
PRIVACY_SETTINGS = {
    'DATA_RETENTION_DAYS': 365,  # How long to keep biometric embeddings
    'AUDIT_LOG_RETENTION_DAYS': 730,  # How long to keep authentication logs (2 years)
    'ALLOW_DATA_EXPORT': True,  # Allow users to export their data (GDPR)
    'ALLOW_DATA_DELETION': True,  # Allow users to delete their data (GDPR)
}

# Logging Configuration for Federated Learning
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'file': {
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'logs' / 'federated_learning.log',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'voting.federated_auth': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'voting.views_federated': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}
